### ISSUE TITLE
Configuração do Docker Compose e Inicialização do Prisma

### ISSUE THREAD

**Issue by CristianoSFMothe** [CristianoSFMothe/todo-list-backend#2]
**Descrição:**
Configurar o ambiente de banco de dados PostgreSQL usando Docker Compose. Inicializar o Prisma no projeto com estrutura padrão (`prisma/schema.prisma`) e configurar o `.env` com a string de conexão correta.

---

### 🔧 Tarefas:

* [x] Criar arquivo `docker-compose.yml` com serviço do PostgreSQL:

  ```yaml
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  ```

* [x] Rodar o container com:

  ```bash
  docker-compose up -d
  ```

* [x] Inicializar o Prisma:

  ```bash
  npx prisma init
  ```

* [x] Criar o arquivo `.env` com variável `DATABASE_URL`:

  ```
  DATABASE_URL="postgresql://user:password@localhost:5432/nestdb"
  ```

* [x] Adicionar `.env` e diretórios gerados ao `.gitignore`.

---

### 📄 Resultado Esperado:

* Banco PostgreSQL disponível localmente via Docker.
* Diretório `prisma/` criado com `schema.prisma` pronto para modelagem.

---

### ✅ Critérios de Aceitação:

* Serviço PostgreSQL acessível.
* Prisma inicializado corretamente.
* String de conexão funcionando para comandos `prisma db` e `generate`.
